---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lrnzwljz/public_html/wp-content
    - /bin/cp -Rf wp-content/plugins/custom-event-registration $DEPLOYPATH/plugins/
    - /bin/cp -Rf wp-content/themes/goodsoul $DEPLOYPATH/themes/
