---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lrnzwljz/public_html/wp-content
    - export REPOPATH=/home/lrnzwljz/repositories/icrhk
    - /bin/mkdir -p $DEPLOYPATH/plugins/custom-event-registration $DEPLOYPATH/themes/goodsoul
    - /bin/cp -Rf $REPOPATH/wp-content/plugins/custom-event-registration/. $DEPLOYPATH/plugins/custom-event-registration/
    - /bin/cp -Rf $REPOPATH/wp-content/themes/goodsoul/. $DEPLOYPATH/themes/goodsoul/
